### PR TITLE
fix: support multi download formats

### LINKED ISSUE #35: Downloads are Always Saved as MP3s
When reviewing the logs from the DownloadManager - I noticed that downloads are saved as .mp3s - even when the source file is FLAC or ALAC.

It would be fantastic if I could also download the files in the original format 

Image

### PR DESCRIPTION
**Pull request by riteshshukla04**
Fixes #35

### CODE REVIEW

File: react-native-nitro-player/ios/download/DownloadFileManager.swift [hunk 1]
```diff
@@ -56,20 +56,28 @@ final class DownloadFileManager {
...
 
-    // Determine file extension from the original URL, not the temp file
-    // The temp file has .tmp extension which AVPlayer cannot play
+    // Determine file extension
     var fileExtension = "mp3"  // Default fallback
-    if let originalURL = originalURL, let url = URL(string: originalURL) {
+
+    if let suggestedFilename = suggestedFilename, !suggestedFilename.isEmpty {
+      let url = URL(fileURLWithPath: suggestedFilename)
+      let pathExtension = url.pathExtension.lowercased()
```
Comment (anultravioletaurora) [inline react-native-nitro-player/ios/download/DownloadFileManager.swift]: Can we get the content type checking on iOS too? :)
